import type {
  RawLiveEvent,
  RawMatchExtras,
  RawPlayerInfo,
  RawRankingRow,
} from '@/services/tennisData/apiShapes';
import { currentUtcMs } from '@/utils/time';

/*
 * Development dataset mirroring the plan §4 wireframes, in raw provider shape
 * so it exercises the same mapping path the ingestion-backed client will use.
 * Start times are relative to now so the order of play stays populated.
 */
function utcIsoHoursFromNow(hours: number): string {
  return new Date(currentUtcMs() + hours * 3_600_000).toISOString();
}

export const SAMPLE_EVENTS: RawLiveEvent[] = [
  {
    id: 1001,
    leagueName: 'ATP Stuttgart',
    tournamentName: 'Stuttgart Open',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-2.2),
    notBefore: false,
    homePlayer: { id: 21, name: 'Bellucci', countryAcr: 'ITA', ranking: 68 },
    awayPlayer: { id: 9, name: 'Fritz', countryAcr: 'USA', seed: 2, ranking: 9 },
    status: 'inprogress',
    setScores: [
      { home: 7, away: 5 },
      { home: 5, away: 7 },
      { home: 5, away: 6 },
    ],
    timeGame: '15-40',
    indicator: 2,
    currentSet: 3,
    elapsedMinutes: 131,
  },
  {
    id: 1002,
    leagueName: 'WTA Hertogenbosch',
    tournamentName: 'Libema Open',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-1.5),
    notBefore: false,
    homePlayer: { id: 61, name: 'McNally', countryAcr: 'USA', ranking: 121 },
    awayPlayer: { id: 62, name: 'Tomljanovic', countryAcr: 'AUS', ranking: 92 },
    status: 'inprogress',
    setScores: [
      { home: 4, away: 6 },
      { home: 1, away: 4 },
    ],
    timeGame: '40-40',
    indicator: 1,
    currentSet: 2,
    elapsedMinutes: 88,
  },
  {
    id: 1003,
    leagueName: 'WTA Queens',
    tournamentName: 'Queens Club Championships',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-0.7),
    notBefore: false,
    homePlayer: { id: 55, name: 'Rybakina', countryAcr: 'KAZ', seed: 4, ranking: 5 },
    awayPlayer: { id: 63, name: 'Boulter', countryAcr: 'GBR', ranking: 41 },
    status: 'inprogress',
    setScores: [{ home: 5, away: 4 }],
    timeGame: '0-30',
    indicator: 2,
    currentSet: 1,
    elapsedMinutes: 41,
  },
  {
    id: 1004,
    leagueName: 'ATP Hertogenbosch',
    tournamentName: 'Libema Open',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-2.1),
    notBefore: false,
    homePlayer: { id: 8, name: 'Medvedev', countryAcr: 'RUS', seed: 1, ranking: 8 },
    awayPlayer: { id: 22, name: 'Cilic', countryAcr: 'CRO', ranking: 80 },
    status: 'inprogress',
    setScores: [
      { home: 6, away: 2 },
      { home: 3, away: 6 },
      { home: 1, away: 1 },
    ],
    timeGame: '30-15',
    indicator: 1,
    currentSet: 3,
    elapsedMinutes: 124,
  },
  {
    id: 1005,
    leagueName: 'Challenger Ilkley',
    tournamentName: 'Ilkley Trophy',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-1.2),
    notBefore: false,
    homePlayer: { id: 23, name: 'Schoolkate', countryAcr: 'AUS', ranking: 105 },
    awayPlayer: { id: 24, name: 'Tarvet', countryAcr: 'GBR', ranking: 719 },
    status: 'inprogress',
    setScores: [
      { home: 3, away: 6 },
      { home: 1, away: 2 },
    ],
    timeGame: '15-0',
    indicator: 2,
    currentSet: 2,
    elapsedMinutes: 71,
  },
  {
    id: 1006,
    leagueName: 'ITF W35 Madrid',
    tournamentName: 'ITF W35 Madrid',
    roundName: 'Quarter-final',
    surface: 'Clay',
    startUtc: utcIsoHoursFromNow(-1.1),
    notBefore: false,
    homePlayer: { id: 64, name: 'Joint', countryAcr: 'AUS', ranking: 81 },
    awayPlayer: { id: 66, name: 'Bartunkova', countryAcr: 'CZE', ranking: 150 },
    status: 'inprogress',
    setScores: [
      { home: 6, away: 3 },
      { home: 2, away: 1 },
    ],
    timeGame: '30-30',
    indicator: 1,
    currentSet: 2,
    elapsedMinutes: 64,
  },
  {
    id: 1007,
    leagueName: 'ATP Halle',
    tournamentName: 'Halle Open',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-0.5),
    notBefore: false,
    homePlayer: { id: 26, name: 'Mannarino', countryAcr: 'FRA', ranking: 25 },
    awayPlayer: { id: 6, name: 'De Minaur', countryAcr: 'AUS', seed: 5, ranking: 6 },
    status: 'inprogress',
    setScores: [{ home: 2, away: 3 }],
    timeGame: '15-30',
    indicator: 2,
    currentSet: 1,
    elapsedMinutes: 32,
  },
  {
    id: 1010,
    leagueName: 'ATP Halle',
    tournamentName: 'Halle Open',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(6.34),
    notBefore: true,
    homePlayer: { id: 7, name: 'Djokovic', countryAcr: 'SRB', seed: 3, ranking: 7 },
    awayPlayer: { id: 25, name: 'Lehecka', countryAcr: 'CZE', ranking: 23 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1011,
    leagueName: 'WTA Queens',
    tournamentName: 'Queens Club Championships',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(8.5),
    notBefore: false,
    homePlayer: { id: 53, name: 'Gauff', countryAcr: 'USA', seed: 2, ranking: 3 },
    awayPlayer: { id: 67, name: 'Keys', countryAcr: 'USA', seed: 6, ranking: 11 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1012,
    leagueName: 'ATP Stuttgart',
    tournamentName: 'Stuttgart Open',
    roundName: 'Final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(13),
    notBefore: true,
    homePlayer: { id: 3, name: 'Zverev', countryAcr: 'GER', seed: 1, ranking: 3 },
    awayPlayer: { id: 5, name: 'Shelton', countryAcr: 'USA', seed: 3, ranking: 5 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1013,
    leagueName: 'Challenger Tucuman',
    tournamentName: 'Tucuman Challenger',
    roundName: 'Quarter-final',
    surface: 'Clay',
    startUtc: utcIsoHoursFromNow(19),
    notBefore: false,
    homePlayer: { id: 28, name: 'Kicker', countryAcr: 'ARG', ranking: 112 },
    awayPlayer: { id: 29, name: 'Coria', countryAcr: 'ARG', ranking: 95 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1020,
    leagueName: 'ATP Halle',
    tournamentName: 'Halle Open',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-10),
    notBefore: false,
    homePlayer: { id: 1, name: 'Sinner', countryAcr: 'ITA', seed: 1, ranking: 1 },
    awayPlayer: { id: 27, name: 'Fonseca', countryAcr: 'BRA', ranking: 17 },
    status: 'finished',
    setScores: [
      { home: 7, away: 6 },
      { home: 7, away: 5 },
    ],
    winner: 1,
  },
  {
    id: 1021,
    leagueName: 'WTA Berlin',
    tournamentName: 'Berlin Open',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-12),
    notBefore: false,
    homePlayer: { id: 54, name: 'Paolini', countryAcr: 'ITA', seed: 4, ranking: 4 },
    awayPlayer: { id: 65, name: 'Anisimova', countryAcr: 'USA', ranking: 12 },
    status: 'finished',
    setScores: [
      { home: 6, away: 3 },
      { home: 6, away: 4 },
    ],
    winner: 1,
  },
  {
    id: 1008,
    leagueName: 'UTR Pro Sydney',
    tournamentName: 'UTR Pro Tennis Tour Sydney',
    roundName: 'Round robin',
    surface: 'Hard',
    startUtc: utcIsoHoursFromNow(-0.9),
    notBefore: false,
    homePlayer: { id: 80, name: 'Saunders', countryAcr: 'AUS' },
    awayPlayer: { id: 81, name: 'McCabe', countryAcr: 'AUS' },
    status: 'inprogress',
    setScores: [
      { home: 6, away: 4 },
      { home: 3, away: 3 },
    ],
    timeGame: '15-15',
    indicator: 1,
    currentSet: 2,
    elapsedMinutes: 58,
  },
  {
    id: 1009,
    leagueName: 'ITF M25 Nottingham',
    tournamentName: 'ITF M25 Nottingham',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-1.7),
    notBefore: false,
    homePlayer: { id: 82, name: 'Loffhagen', countryAcr: 'GBR', ranking: 282 },
    awayPlayer: { id: 83, name: 'Peniston', countryAcr: 'GBR', ranking: 311 },
    status: 'inprogress',
    setScores: [
      { home: 6, away: 7 },
      { home: 4, away: 2 },
    ],
    timeGame: '30-0',
    indicator: 2,
    currentSet: 2,
    elapsedMinutes: 96,
  },
  {
    id: 1014,
    leagueName: 'WTA Berlin',
    tournamentName: 'Berlin Open',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-0.4),
    notBefore: false,
    homePlayer: { id: 56, name: 'Pegula', countryAcr: 'USA', seed: 3, ranking: 6 },
    awayPlayer: { id: 77, name: 'Vekic', countryAcr: 'CRO', ranking: 20 },
    status: 'inprogress',
    setScores: [{ home: 3, away: 2 }],
    timeGame: '40-15',
    indicator: 1,
    currentSet: 1,
    elapsedMinutes: 27,
  },
  {
    id: 1015,
    leagueName: 'ATP Halle',
    tournamentName: 'Halle Open',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(22),
    notBefore: false,
    homePlayer: { id: 1, name: 'Sinner', countryAcr: 'ITA', seed: 1, ranking: 1 },
    awayPlayer: { id: 10, name: 'Rune', countryAcr: 'DEN', seed: 7, ranking: 10 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1016,
    leagueName: 'WTA Berlin',
    tournamentName: 'Berlin Open',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(9),
    notBefore: false,
    homePlayer: { id: 51, name: 'Sabalenka', countryAcr: 'BLR', seed: 1, ranking: 1 },
    awayPlayer: { id: 54, name: 'Paolini', countryAcr: 'ITA', seed: 4, ranking: 4 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1017,
    leagueName: 'Challenger Ilkley',
    tournamentName: 'Ilkley Trophy',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(10.5),
    notBefore: true,
    homePlayer: { id: 84, name: 'Kasnikowski', countryAcr: 'POL', ranking: 134 },
    awayPlayer: { id: 85, name: 'Watanuki', countryAcr: 'JPN', ranking: 152 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1018,
    leagueName: 'ITF W35 Madrid',
    tournamentName: 'ITF W35 Madrid',
    roundName: 'Final',
    surface: 'Clay',
    startUtc: utcIsoHoursFromNow(21),
    notBefore: false,
    homePlayer: { id: 86, name: 'Sakatsume', countryAcr: 'JPN', ranking: 188 },
    awayPlayer: { id: 87, name: 'Back', countryAcr: 'KOR', ranking: 203 },
    status: 'notstarted',
    setScores: [],
  },
  {
    id: 1022,
    leagueName: 'ATP Stuttgart',
    tournamentName: 'Stuttgart Open',
    roundName: 'Semi-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-9),
    notBefore: false,
    homePlayer: { id: 3, name: 'Zverev', countryAcr: 'GER', seed: 1, ranking: 3 },
    awayPlayer: { id: 4, name: 'Auger-Aliassime', countryAcr: 'CAN', seed: 4, ranking: 4 },
    status: 'finished',
    setScores: [
      { home: 6, away: 4 },
      { home: 7, away: 6 },
    ],
    winner: 1,
  },
  {
    id: 1023,
    leagueName: 'WTA Queens',
    tournamentName: 'Queens Club Championships',
    roundName: 'Quarter-final',
    surface: 'Grass',
    startUtc: utcIsoHoursFromNow(-11),
    notBefore: false,
    homePlayer: { id: 67, name: 'Keys', countryAcr: 'USA', seed: 6, ranking: 11 },
    awayPlayer: { id: 88, name: 'Raducanu', countryAcr: 'GBR', ranking: 38 },
    status: 'finished',
    setScores: [
      { home: 6, away: 3 },
      { home: 4, away: 6 },
      { home: 7, away: 5 },
    ],
    winner: 1,
  },
  {
    id: 1024,
    leagueName: 'Challenger Tucuman',
    tournamentName: 'Tucuman Challenger',
    roundName: 'Quarter-final',
    surface: 'Clay',
    startUtc: utcIsoHoursFromNow(-13),
    notBefore: false,
    homePlayer: { id: 89, name: 'Navone', countryAcr: 'ARG', ranking: 77 },
    awayPlayer: { id: 90, name: 'Diaz Acosta', countryAcr: 'ARG', ranking: 84 },
    status: 'finished',
    setScores: [
      { home: 6, away: 3 },
      { home: 6, away: 2 },
    ],
    winner: 1,
  },
];

export const SAMPLE_ATP_RANKINGS: RawRankingRow[] = [
  { position: 1, playerId: 1, playerName: 'Jannik Sinner', countryAcr: 'ITA', points: 13500, movement: 0 },
  { position: 2, playerId: 2, playerName: 'Carlos Alcaraz', countryAcr: 'ESP', points: 9960, movement: 0 },
  { position: 3, playerId: 3, playerName: 'Alexander Zverev', countryAcr: 'GER', points: 7305, movement: 0 },
  { position: 4, playerId: 4, playerName: 'Felix Auger-Aliassime', countryAcr: 'CAN', points: 4440, movement: 2 },
  { position: 5, playerId: 5, playerName: 'Ben Shelton', countryAcr: 'USA', points: 3920, movement: -1 },
  { position: 6, playerId: 6, playerName: 'Alex de Minaur', countryAcr: 'AUS', points: 3905, movement: 0 },
  { position: 7, playerId: 7, playerName: 'Novak Djokovic', countryAcr: 'SRB', points: 3760, movement: 1 },
  { position: 8, playerId: 8, playerName: 'Daniil Medvedev', countryAcr: 'RUS', points: 3760, movement: -1 },
  { position: 9, playerId: 9, playerName: 'Taylor Fritz', countryAcr: 'USA', points: 3690, movement: 0 },
  { position: 10, playerId: 10, playerName: 'Holger Rune', countryAcr: 'DEN', points: 3440, movement: 0 },
  { position: 11, playerId: 11, playerName: 'Jack Draper', countryAcr: 'GBR', points: 2990, movement: 1 },
  { position: 12, playerId: 12, playerName: 'Lorenzo Musetti', countryAcr: 'ITA', points: 2860, movement: -1 },
  { position: 13, playerId: 13, playerName: 'Hubert Hurkacz', countryAcr: 'POL', points: 2700, movement: 0 },
  { position: 14, playerId: 14, playerName: 'Andrey Rublev', countryAcr: 'RUS', points: 2620, movement: 0 },
  { position: 15, playerId: 15, playerName: 'Stefanos Tsitsipas', countryAcr: 'GRE', points: 2455, movement: -3 },
  { position: 16, playerId: 16, playerName: 'Jakub Mensik', countryAcr: 'CZE', points: 2380, movement: 2 },
  { position: 17, playerId: 27, playerName: 'Joao Fonseca', countryAcr: 'BRA', points: 2290, movement: 4 },
  { position: 18, playerId: 18, playerName: 'Karen Khachanov', countryAcr: 'RUS', points: 2210, movement: 0 },
  { position: 19, playerId: 19, playerName: 'Frances Tiafoe', countryAcr: 'USA', points: 2135, movement: -1 },
  { position: 20, playerId: 20, playerName: 'Francisco Cerundolo', countryAcr: 'ARG', points: 2080, movement: -1 },
];

export const SAMPLE_WTA_RANKINGS: RawRankingRow[] = [
  { position: 1, playerId: 51, playerName: 'Aryna Sabalenka', countryAcr: 'BLR', points: 11553, movement: 0 },
  { position: 2, playerId: 52, playerName: 'Iga Swiatek', countryAcr: 'POL', points: 8093, movement: 0 },
  { position: 3, playerId: 53, playerName: 'Coco Gauff', countryAcr: 'USA', points: 7669, movement: 0 },
  { position: 4, playerId: 54, playerName: 'Jasmine Paolini', countryAcr: 'ITA', points: 4805, movement: 1 },
  { position: 5, playerId: 55, playerName: 'Elena Rybakina', countryAcr: 'KAZ', points: 4400, movement: -1 },
  { position: 6, playerId: 56, playerName: 'Jessica Pegula', countryAcr: 'USA', points: 4185, movement: 0 },
  { position: 7, playerId: 57, playerName: 'Mirra Andreeva', countryAcr: 'RUS', points: 4119, movement: 0 },
  { position: 8, playerId: 58, playerName: 'Qinwen Zheng', countryAcr: 'CHN', points: 4066, movement: 0 },
  { position: 9, playerId: 59, playerName: 'Paula Badosa', countryAcr: 'ESP', points: 3221, movement: 2 },
  { position: 10, playerId: 60, playerName: 'Emma Navarro', countryAcr: 'USA', points: 3058, movement: -1 },
  { position: 11, playerId: 67, playerName: 'Madison Keys', countryAcr: 'USA', points: 2967, movement: 0 },
  { position: 12, playerId: 65, playerName: 'Amanda Anisimova', countryAcr: 'USA', points: 2956, movement: 1 },
  { position: 13, playerId: 68, playerName: 'Elina Svitolina', countryAcr: 'UKR', points: 2856, movement: -1 },
  { position: 14, playerId: 69, playerName: 'Ekaterina Alexandrova', countryAcr: 'RUS', points: 2611, movement: 0 },
  { position: 15, playerId: 70, playerName: 'Liudmila Samsonova', countryAcr: 'RUS', points: 2480, movement: 0 },
  { position: 16, playerId: 71, playerName: 'Jelena Ostapenko', countryAcr: 'LAT', points: 2351, movement: 2 },
  { position: 17, playerId: 72, playerName: 'Karolina Muchova', countryAcr: 'CZE', points: 2270, movement: 0 },
  { position: 18, playerId: 73, playerName: 'Barbora Krejcikova', countryAcr: 'CZE', points: 2118, movement: -2 },
  { position: 19, playerId: 74, playerName: 'Beatriz Haddad Maia', countryAcr: 'BRA', points: 2056, movement: 0 },
  { position: 20, playerId: 77, playerName: 'Donna Vekic', countryAcr: 'CRO', points: 1985, movement: 1 },
];

export const SAMPLE_PLAYER_PROFILES: RawPlayerInfo[] = [
  {
    id: 7,
    name: 'Novak Djokovic',
    country: 'Serbia',
    plays: 'Right-handed',
    turnedPro: 2003,
    currentRank: 7,
    points: 3760,
    form: 'WWLWWWLWWW',
    surfaceWins: { hard: 84, clay: 80, grass: 86 },
    titles: 100,
    grandSlams: 24,
  },
  {
    id: 1,
    name: 'Jannik Sinner',
    country: 'Italy',
    plays: 'Right-handed',
    turnedPro: 2018,
    currentRank: 1,
    points: 13500,
    form: 'WWWWWWWLWW',
    surfaceWins: { hard: 86, clay: 78, grass: 84 },
    titles: 25,
    grandSlams: 4,
  },
  {
    id: 2,
    name: 'Carlos Alcaraz',
    country: 'Spain',
    plays: 'Right-handed',
    turnedPro: 2018,
    currentRank: 2,
    points: 9960,
    form: 'WWWWLWWWWW',
    surfaceWins: { hard: 82, clay: 85, grass: 88 },
    titles: 21,
    grandSlams: 5,
  },
  {
    id: 6,
    name: 'Alex de Minaur',
    country: 'Australia',
    plays: 'Right-handed',
    turnedPro: 2015,
    currentRank: 6,
    points: 3905,
    form: 'WLWWLWWWLW',
    surfaceWins: { hard: 71, clay: 64, grass: 73 },
    titles: 9,
    grandSlams: 0,
  },
];

export const SAMPLE_MATCH_EXTRAS: Record<number, RawMatchExtras> = {
  1001: {
    momentum: [1, 2, 5, 3, 2, 6, 7, 3, 2, 1, 5, 6, 2, 3, 5],
    timeline: [
      { games: '5-6', points: '0-15', note: 'Double fault' },
      { games: '5-6', points: '15-15', note: 'Ace — his 11th' },
      { games: '5-6', points: '15-30', note: 'Forehand winner' },
      { games: '5-6', points: '15-40', note: 'Backhand long — two break points' },
    ],
    stats: {
      aces: [3, 11],
      doubleFaults: [4, 2],
      firstServePct: [61, 72],
      breakPointsWon: [3, 4],
      winners: [22, 31],
      unforcedErrors: [27, 19],
    },
    h2h: {
      wins: [1, 3],
      meetings: [
        { year: 2025, eventName: 'Tokyo R16', winner: 2, score: '6-3 6-4' },
        { year: 2024, eventName: 'US Open R64', winner: 2, score: '7-6 6-4 6-2' },
        { year: 2024, eventName: 'Naples Final', winner: 1, score: '6-4 3-6 7-6' },
      ],
    },
    storyline: 'Fritz leads the head-to-head 3–1, but is 0–1 on grass.',
  },
  1010: {
    momentum: [],
    timeline: [],
    h2h: {
      wins: [2, 0],
      meetings: [
        { year: 2025, eventName: 'Australian Open QF', winner: 1, score: '6-3 4-6 6-4 7-6' },
        { year: 2023, eventName: 'Adelaide Final', winner: 1, score: '7-6 6-7 6-4' },
      ],
    },
    storyline: 'Djokovic and Lehecka have met twice; both went the distance.',
  },
};
